kind: Service
apiVersion: v1
metadata:
  name: springboot-load-service
spec:
  ports:
    - port: 80 
      targetPort: 8080
  selector:
    type: backend
    app: springbootdocker  
  type: LoadBalancer         
